spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ai_platform
spring.datasource.username=root
spring.datasource.password=SAMIR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
